{% set name = "dxcam" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dxcam-{{ version }}.tar.gz
  sha256: 1078d205f096b9d6911c39985ac9298b6fce837bc50e38327bf4600661f5b34c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - pip
  run:
    - python >=3.7
    - numpy
    - opencv
    - comtypes
    - __win

test:
  imports:
    - dxcam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ra1nty/DXcam
  summary: A Python high-performance screenshot library for Windows use Desktop Duplication API
  dev_url: https://github.com/ra1nty/DXcam
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
